language: php
php: 
- "5.4"
sudo: false
script:
- ./scripts/update-children.sh
branches:
  only:
    - master
notifications:
  email:
    recipients: 
      - jesse@launchcode.org
    on_success: never
    on_failure: change
    
